# Test your FastAPI endpoints

GET http://127.0.0.1:8000/docs
Accept: application/json

###

POST http://127.0.0.1:8000/process-message
Accept: application/json

{
  "content": "سلام، سیستم مرخصی من خطا می‌ده و نمی‌تونم مرخصی ثبت کنم."
}
###

POST http://127.0.0.1:8000/langchain-sample1
Accept: application/json

{
  "content": "سلام، سیستم مرخصی من خطا می‌ده و نمی‌تونم مرخصی ثبت کنم."
}
###

POST http://127.0.0.1:8000/langchain-sample2
Accept: application/json

{
  "content": "سلام، سیستم مرخصی من خطا می‌ده و نمی‌تونم مرخصی ثبت کنم."
}
###

POST http://127.0.0.1:8000/langchain-sample3
Accept: application/json

{
  "content": "سلام، سیستم مرخصی من خطا می‌ده و نمی‌تونم مرخصی ثبت کنم."
}
###

POST http://127.0.0.1:8000/langchain-sample4
Accept: application/json

{
  "content": "مودم تی پی لینک رو چه جوری تنظیم کنم؟",
  "path":"mehdi"
}
###

GET http://127.0.0.1:8000/memory/receptionist
Accept: application/json

###
